### ISSUE TITLE
Create usage documentation guide

### ISSUE THREAD

**Issue by beesaferoot** [EnAccess/OpenPAYGO-js#10]
We need to update the ReadME to contain comprehensive usage guide and clean up instructions not related to the package.

**Comment by dmohns** [comment]
I would like to put the "user facing" guide on how to use this library into the common, shared OpenPAYGO documentation here: https://enaccess.github.io/OpenPAYGO-docs/docs/openpaygo-token/ This would probably require a little bit of restructuring of the docs, as they currently don't have a implementation specific section.

In the README in this repo we can keep the developer related documentation, i.e. for people that want to contribute to the library it self.

**Comment by beesaferoot** [comment]
> I would like to put the "user facing" guide on how to use this library into the common, shared OpenPAYGO documentation here: https://enaccess.github.io/OpenPAYGO-docs/docs/openpaygo-token/ This would probably require a little bit of restructuring of the docs, as they currently don't have a implementation specific section.

In that case I would do the other part i.e "get started" and contributions. 

 
I will make an initial draft for this and check again with you. Thanks
