### ISSUE TITLE
Create website for testing Token generation

### ISSUE THREAD

**Issue by dmohns** [EnAccess/OpenPAYGO-js#16]
Create a small static (!) website which can be used to generate OpenPAYGO Tokens for a testing use-case. The result should be similar to the example from Victron: https://payg.victronenergy.com/ (however Tokens should be computed client side, not server side like in the Victron case).

We can use this repository's Github page to host the website.

**Comment by munyanezaarmel** [comment]
@dmohns can I take this

**Comment by dmohns** [comment]
Hey @munyanezaarmel absolutely! Thanks, I assigned you
