### ISSUE TITLE
[CI] Integrate package release job 

### ISSUE THREAD

**Issue by beesaferoot** [EnAccess/OpenPAYGO-js#9]
Tests are now stable. We can now create a v0.0.1 release on npm as is.

Tasks:
- Create or use existing npm account
- Setup CI job for version release (tagging, upload to npm)

**Comment by dmohns** [comment]
Good news 🥳 I will take care of this as I would like to host this under EnAccess NPM account. 

I think it would be great to do this after we improved the `README` file a little bit, i.e. https://github.com/EnAccess/OpenPAYGO-js/issues/10

**Comment by beesaferoot** [comment]
Alright, sounds good to me.

**Comment by beesaferoot** [comment]
> Hey @beesaferoot I went ahead and configured this. We now have it available on NPM: https://www.npmjs.com/package/openpaygo

🥳 This is great, thank you @dmohns 

I can now get around updating the READMe
